CREATE TABLESPACE SALESTS IN Z88116;
CREATE TABLE Z88116.SALES_DATA (
    CUST_ID     CHAR(5)                 NOT NULL,
    CATEGORY    VARCHAR(10)             NOT NULL,
    QUANTITY    INTEGER                 NOT NULL,
    UNIT_PRICE  DECIMAL(6,2)            NOT NULL
) IN Z88116.SALESTS;
CREATE TABLESPACE VALTS IN Z88116;
CREATE TABLE Z88116.VALID_SALES (
    CUST_ID     CHAR(5)                 NOT NULL,
    CATEGORY    VARCHAR(10)             NOT NULL,
    DISC_PRICE  DECIMAL(9,2)            NOT NULL
) IN Z88116.VALTS;
CREATE TABLESPACE ERRTS IN Z88116;
CREATE TABLE Z88116.ERROR_LOG (
    ERR_DATA    VARCHAR(24)             NOT NULL,
    ERR_REASON  VARCHAR(20)             NOT NULL
) IN Z88116.ERRTS;